// Diamond Proxy ABI - основные функции для фронтенда
export const DIAMOND_ABI = [
  // === RegistryFacet ===
  {
    inputs: [
      { internalType: 'address', name: 'client', type: 'address' },
      { internalType: 'address', name: 'executor', type: 'address' },
    ],
    name: 'hasActivePair',
    outputs: [{ internalType: 'bool', name: '', type: 'bool' }],
    stateMutability: 'view',
    type: 'function',
  },
  {
    inputs: [
      { internalType: 'address', name: 'client', type: 'address' },
      { internalType: 'address', name: 'executor', type: 'address' },
    ],
    name: 'getActivePair',
    outputs: [{ internalType: 'address', name: '', type: 'address' }],
    stateMutability: 'view',
    type: 'function',
  },
  {
    inputs: [{ internalType: 'address', name: 'agreement', type: 'address' }],
    name: 'getRecord',
    outputs: [
      {
        components: [
          { internalType: 'address', name: 'agreement', type: 'address' },
          { internalType: 'address', name: 'client', type: 'address' },
          { internalType: 'address', name: 'executor', type: 'address' },
          { internalType: 'uint256', name: 'amount', type: 'uint256' },
          { internalType: 'uint8', name: 'status', type: 'uint8' },
          { internalType: 'uint256', name: 'createdAt', type: 'uint256' },
          { internalType: 'uint256', name: 'resolvedAt', type: 'uint256' },
        ],
        internalType: 'struct RegistryStorage.AgreementRecord',
        name: '',
        type: 'tuple',
      },
    ],
    stateMutability: 'view',
    type: 'function',
  },
  {
    inputs: [{ internalType: 'address', name: 'client', type: 'address' }],
    name: 'getByClient',
    outputs: [
      {
        components: [
          { internalType: 'address', name: 'agreement', type: 'address' },
          { internalType: 'address', name: 'client', type: 'address' },
          { internalType: 'address', name: 'executor', type: 'address' },
          { internalType: 'uint256', name: 'amount', type: 'uint256' },
          { internalType: 'uint8', name: 'status', type: 'uint8' },
          { internalType: 'uint256', name: 'createdAt', type: 'uint256' },
          { internalType: 'uint256', name: 'resolvedAt', type: 'uint256' },
        ],
        internalType: 'struct RegistryStorage.AgreementRecord[]',
        name: '',
        type: 'tuple[]',
      },
    ],
    stateMutability: 'view',
    type: 'function',
  },
  {
    inputs: [{ internalType: 'address', name: 'executor', type: 'address' }],
    name: 'getByExecutor',
    outputs: [
      {
        components: [
          { internalType: 'address', name: 'agreement', type: 'address' },
          { internalType: 'address', name: 'client', type: 'address' },
          { internalType: 'address', name: 'executor', type: 'address' },
          { internalType: 'uint256', name: 'amount', type: 'uint256' },
          { internalType: 'uint8', name: 'status', type: 'uint8' },
          { internalType: 'uint256', name: 'createdAt', type: 'uint256' },
          { internalType: 'uint256', name: 'resolvedAt', type: 'uint256' },
        ],
        internalType: 'struct RegistryStorage.AgreementRecord[]',
        name: '',
        type: 'tuple[]',
      },
    ],
    stateMutability: 'view',
    type: 'function',
  },
  {
    inputs: [],
    name: 'getActive',
    outputs: [
      {
        components: [
          { internalType: 'address', name: 'agreement', type: 'address' },
          { internalType: 'address', name: 'client', type: 'address' },
          { internalType: 'address', name: 'executor', type: 'address' },
          { internalType: 'uint256', name: 'amount', type: 'uint256' },
          { internalType: 'uint8', name: 'status', type: 'uint8' },
          { internalType: 'uint256', name: 'createdAt', type: 'uint256' },
          { internalType: 'uint256', name: 'resolvedAt', type: 'uint256' },
        ],
        internalType: 'struct RegistryStorage.AgreementRecord[]',
        name: '',
        type: 'tuple[]',
      },
    ],
    stateMutability: 'view',
    type: 'function',
  },
  {
    inputs: [],
    name: 'totalAgreements',
    outputs: [{ internalType: 'uint256', name: '', type: 'uint256' }],
    stateMutability: 'view',
    type: 'function',
  },
  {
    inputs: [],
    name: 'getDisputed',
    outputs: [
      {
        components: [
          { internalType: 'address', name: 'agreement', type: 'address' },
          { internalType: 'address', name: 'client', type: 'address' },
          { internalType: 'address', name: 'executor', type: 'address' },
          { internalType: 'uint256', name: 'amount', type: 'uint256' },
          { internalType: 'uint8', name: 'status', type: 'uint8' },
          { internalType: 'uint256', name: 'createdAt', type: 'uint256' },
          { internalType: 'uint256', name: 'resolvedAt', type: 'uint256' },
        ],
        internalType: 'struct RegistryStorage.AgreementRecord[]',
        name: '',
        type: 'tuple[]',
      },
    ],
    stateMutability: 'view',
    type: 'function',
  },

  // === FactoryFacet ===
  {
    inputs: [
      { internalType: 'address', name: 'client', type: 'address' },
      { internalType: 'address', name: 'executor', type: 'address' },
      { internalType: 'address', name: 'arbiter', type: 'address' },
      { internalType: 'uint256', name: 'amount', type: 'uint256' },
      { internalType: 'uint256', name: 'deadlineDays', type: 'uint256' },
      { internalType: 'bytes32', name: 'termsHash', type: 'bytes32' },
      { internalType: 'uint8', name: 'region', type: 'uint8' },
    ],
    name: 'deployAgreement',
    outputs: [{ internalType: 'address', name: 'agreementAddress', type: 'address' }],
    stateMutability: 'nonpayable',
    type: 'function',
  },
  {
    inputs: [
      { internalType: 'address', name: 'client', type: 'address' },
      { internalType: 'address', name: 'executor', type: 'address' },
      { internalType: 'uint256', name: 'amount', type: 'uint256' },
      { internalType: 'uint256', name: 'deadlineDays', type: 'uint256' },
      { internalType: 'bytes32', name: 'termsHash', type: 'bytes32' },
      { internalType: 'uint8', name: 'region', type: 'uint8' },
      { internalType: 'uint256', name: 'permitDeadline', type: 'uint256' },
      { internalType: 'uint8', name: 'v', type: 'uint8' },
      { internalType: 'bytes32', name: 'r', type: 'bytes32' },
      { internalType: 'bytes32', name: 's', type: 'bytes32' },
    ],
    name: 'deployAndFund',
    outputs: [{ internalType: 'address', name: 'agreementAddress', type: 'address' }],
    stateMutability: 'nonpayable',
    type: 'function',
  },
  {
    inputs: [{ internalType: 'uint8', name: 'region', type: 'uint8' }],
    name: 'getRegionFee',
    outputs: [{ internalType: 'uint256', name: '', type: 'uint256' }],
    stateMutability: 'view',
    type: 'function',
  },
  {
    inputs: [],
    name: 'getAllFees',
    outputs: [
      { internalType: 'uint256', name: 'cis', type: 'uint256' },
      { internalType: 'uint256', name: 'asia', type: 'uint256' },
      { internalType: 'uint256', name: 'eu', type: 'uint256' },
      { internalType: 'uint256', name: 'us', type: 'uint256' },
      { internalType: 'uint256', name: 'latam', type: 'uint256' },
      { internalType: 'uint256', name: 'ca', type: 'uint256' },
      { internalType: 'uint256', name: 'au', type: 'uint256' },
    ],
    stateMutability: 'view',
    type: 'function',
  },
  {
    inputs: [],
    name: 'getUsdc',
    outputs: [{ internalType: 'address', name: '', type: 'address' }],
    stateMutability: 'view',
    type: 'function',
  },
  {
    inputs: [],
    name: 'getTrustedForwarder',
    outputs: [{ internalType: 'address', name: '', type: 'address' }],
    stateMutability: 'view',
    type: 'function',
  },
  {
    inputs: [{ internalType: 'address', name: 'newRecipient', type: 'address' }],
    name: 'setFeeRecipient',
    outputs: [],
    stateMutability: 'nonpayable',
    type: 'function',
  },
  {
    inputs: [{ internalType: 'address', name: 'newForwarder', type: 'address' }],
    name: 'setTrustedForwarder',
    outputs: [],
    stateMutability: 'nonpayable',
    type: 'function',
  },
  {
    inputs: [],
    name: 'getFeeRecipient',
    outputs: [{ internalType: 'address', name: '', type: 'address' }],
    stateMutability: 'view',
    type: 'function',
  },
  {
    inputs: [],
    name: 'isPaused',
    outputs: [{ internalType: 'bool', name: '', type: 'bool' }],
    stateMutability: 'view',
    type: 'function',
  },
  {
    inputs: [{ internalType: 'bool', name: '_paused', type: 'bool' }],
    name: 'setPaused',
    outputs: [],
    stateMutability: 'nonpayable',
    type: 'function',
  },
  {
    inputs: [{ internalType: 'address', name: 'arbiter', type: 'address' }],
    name: 'setProtocolArbiter',
    outputs: [],
    stateMutability: 'nonpayable',
    type: 'function',
  },
  {
    inputs: [],
    name: 'getProtocolArbiter',
    outputs: [{ internalType: 'address', name: '', type: 'address' }],
    stateMutability: 'view',
    type: 'function',
  },
  {
    inputs: [{ internalType: 'uint256', name: 'newThreshold', type: 'uint256' }],
    name: 'setArbitrationThreshold',
    outputs: [],
    stateMutability: 'nonpayable',
    type: 'function',
  },
  {
    inputs: [],
    name: 'getArbitrationThreshold',
    outputs: [{ internalType: 'uint256', name: '', type: 'uint256' }],
    stateMutability: 'view',
    type: 'function',
  },
  {
    inputs: [
      { internalType: 'uint8', name: 'region', type: 'uint8' },
      { internalType: 'uint256', name: 'newFee', type: 'uint256' },
    ],
    name: 'setRegionFee',
    outputs: [],
    stateMutability: 'nonpayable',
    type: 'function',
  },

  // === ServiceBoardFacet ===
  {
    inputs: [
      { internalType: 'string', name: 'title', type: 'string' },
      { internalType: 'string', name: 'description', type: 'string' },
      { internalType: 'uint256', name: 'price', type: 'uint256' },
      { internalType: 'uint256', name: 'deadlineDays', type: 'uint256' },
      { internalType: 'uint8', name: 'region', type: 'uint8' },
    ],
    name: 'mintService',
    outputs: [{ internalType: 'uint256', name: 'serviceId', type: 'uint256' }],
    stateMutability: 'nonpayable',
    type: 'function',
  },
  {
    inputs: [
      { internalType: 'address', name: 'executor', type: 'address' },
      { internalType: 'string', name: 'title', type: 'string' },
      { internalType: 'string', name: 'description', type: 'string' },
      { internalType: 'uint256', name: 'price', type: 'uint256' },
      { internalType: 'uint256', name: 'deadlineDays', type: 'uint256' },
      { internalType: 'uint8', name: 'region', type: 'uint8' },
      { internalType: 'uint256', name: 'permitDeadline', type: 'uint256' },
      { internalType: 'uint8', name: 'v', type: 'uint8' },
      { internalType: 'bytes32', name: 'r', type: 'bytes32' },
      { internalType: 'bytes32', name: 's', type: 'bytes32' },
    ],
    name: 'mintServiceWithPermit',
    outputs: [{ internalType: 'uint256', name: 'serviceId', type: 'uint256' }],
    stateMutability: 'nonpayable',
    type: 'function',
  },
  {
    inputs: [
      { internalType: 'uint256', name: 'serviceId', type: 'uint256' },
      { internalType: 'uint256', name: 'amount', type: 'uint256' },
      { internalType: 'uint256', name: 'deadlineDays', type: 'uint256' },
      { internalType: 'bytes32', name: 'termsHash', type: 'bytes32' },
      { internalType: 'uint8', name: 'region', type: 'uint8' },
    ],
    name: 'requestService',
    outputs: [{ internalType: 'uint256', name: 'requestId', type: 'uint256' }],
    stateMutability: 'nonpayable',
    type: 'function',
  },
  {
    inputs: [
      { internalType: 'address',  name: 'client',        type: 'address'  },
      { internalType: 'uint256',  name: 'serviceId',     type: 'uint256'  },
      { internalType: 'uint256',  name: 'amount',        type: 'uint256'  },
      { internalType: 'uint256',  name: 'deadlineDays',  type: 'uint256'  },
      { internalType: 'bytes32',  name: 'termsHash',     type: 'bytes32'  },
      { internalType: 'uint8',    name: 'region',        type: 'uint8'    },
      { internalType: 'uint256',  name: 'permitDeadline', type: 'uint256' },
      { internalType: 'uint8',    name: 'v',             type: 'uint8'    },
      { internalType: 'bytes32',  name: 'r',             type: 'bytes32'  },
      { internalType: 'bytes32',  name: 's',             type: 'bytes32'  },
    ],
    name: 'requestServiceWithPermit',
    outputs: [{ internalType: 'uint256', name: 'requestId', type: 'uint256' }],
    stateMutability: 'nonpayable',
    type: 'function',
  },
  {
    inputs: [{ internalType: 'uint256', name: 'requestId', type: 'uint256' }],
    name: 'acceptRequest',
    outputs: [{ internalType: 'address', name: 'agreementAddr', type: 'address' }],
    stateMutability: 'nonpayable',
    type: 'function',
  },
  {
    inputs: [{ internalType: 'uint256', name: 'requestId', type: 'uint256' }],
    name: 'rejectRequest',
    outputs: [],
    stateMutability: 'nonpayable',
    type: 'function',
  },
  {
    inputs: [{ internalType: 'uint256', name: 'requestId', type: 'uint256' }],
    name: 'cancelRequest',
    outputs: [],
    stateMutability: 'nonpayable',
    type: 'function',
  },
  {
    inputs: [{ internalType: 'uint256', name: 'serviceId', type: 'uint256' }],
    name: 'removeService',
    outputs: [],
    stateMutability: 'nonpayable',
    type: 'function',
  },
  {
    inputs: [{ internalType: 'uint256', name: 'serviceId', type: 'uint256' }],
    name: 'pauseService',
    outputs: [],
    stateMutability: 'nonpayable',
    type: 'function',
  },
  {
    inputs: [{ internalType: 'uint256', name: 'serviceId', type: 'uint256' }],
    name: 'unpauseService',
    outputs: [],
    stateMutability: 'nonpayable',
    type: 'function',
  },
  {
    inputs: [{ internalType: 'uint256', name: 'serviceId', type: 'uint256' }],
    name: 'getService',
    outputs: [
      {
        components: [
          { internalType: 'address', name: 'executor', type: 'address' },
          { internalType: 'string', name: 'title', type: 'string' },
          { internalType: 'string', name: 'description', type: 'string' },
          { internalType: 'uint256', name: 'price', type: 'uint256' },
          { internalType: 'uint256', name: 'deadlineDays', type: 'uint256' },
          { internalType: 'uint8', name: 'region', type: 'uint8' },
          { internalType: 'uint8', name: 'status', type: 'uint8' },
          { internalType: 'uint256', name: 'createdAt', type: 'uint256' },
          { internalType: 'uint256', name: 'hiresCount', type: 'uint256' },
        ],
        internalType: 'struct ServiceBoardStorage.Service',
        name: '',
        type: 'tuple',
      },
    ],
    stateMutability: 'view',
    type: 'function',
  },
  {
    inputs: [{ internalType: 'uint256', name: 'requestId', type: 'uint256' }],
    name: 'getRequest',
    outputs: [
      {
        components: [
          { internalType: 'address', name: 'client', type: 'address' },
          { internalType: 'uint256', name: 'serviceId', type: 'uint256' },
          { internalType: 'uint256', name: 'amount', type: 'uint256' },
          { internalType: 'uint256', name: 'deadlineDays', type: 'uint256' },
          { internalType: 'bytes32', name: 'termsHash', type: 'bytes32' },
          { internalType: 'uint8', name: 'region', type: 'uint8' },
          { internalType: 'uint8', name: 'status', type: 'uint8' },
          { internalType: 'uint256', name: 'createdAt', type: 'uint256' },
          { internalType: 'address', name: 'agreement', type: 'address' },
        ],
        internalType: 'struct ServiceBoardStorage.HireRequest',
        name: '',
        type: 'tuple',
      },
    ],
    stateMutability: 'view',
    type: 'function',
  },
  {
    inputs: [{ internalType: 'address', name: 'executor', type: 'address' }],
    name: 'getExecutorServices',
    outputs: [{ internalType: 'uint256[]', name: '', type: 'uint256[]' }],
    stateMutability: 'view',
    type: 'function',
  },
  {
    inputs: [{ internalType: 'address', name: 'client', type: 'address' }],
    name: 'getClientRequests',
    outputs: [{ internalType: 'uint256[]', name: '', type: 'uint256[]' }],
    stateMutability: 'view',
    type: 'function',
  },
  {
    inputs: [{ internalType: 'uint256', name: 'serviceId', type: 'uint256' }],
    name: 'getServiceRequests',
    outputs: [{ internalType: 'uint256[]', name: '', type: 'uint256[]' }],
    stateMutability: 'view',
    type: 'function',
  },
  {
    inputs: [],
    name: 'totalServices',
    outputs: [{ internalType: 'uint256', name: '', type: 'uint256' }],
    stateMutability: 'view',
    type: 'function',
  },
  {
    inputs: [],
    name: 'totalRequests',
    outputs: [{ internalType: 'uint256', name: '', type: 'uint256' }],
    stateMutability: 'view',
    type: 'function',
  },
  {
    inputs: [],
    name: 'getActiveServices',
    outputs: [
      { internalType: 'uint256[]', name: 'ids', type: 'uint256[]' },
      {
        components: [
          { internalType: 'address', name: 'executor', type: 'address' },
          { internalType: 'string', name: 'title', type: 'string' },
          { internalType: 'string', name: 'description', type: 'string' },
          { internalType: 'uint256', name: 'price', type: 'uint256' },
          { internalType: 'uint256', name: 'deadlineDays', type: 'uint256' },
          { internalType: 'uint8', name: 'region', type: 'uint8' },
          { internalType: 'uint8', name: 'status', type: 'uint8' },
          { internalType: 'uint256', name: 'createdAt', type: 'uint256' },
          { internalType: 'uint256', name: 'hiresCount', type: 'uint256' },
        ],
        internalType: 'struct ServiceBoardStorage.Service[]',
        name: 'activeServices',
        type: 'tuple[]',
      },
    ],
    stateMutability: 'view',
    type: 'function',
  },
  {
    inputs: [{ internalType: 'uint256', name: 'serviceId', type: 'uint256' }],
    name: 'getPendingRequests',
    outputs: [
      { internalType: 'uint256[]', name: 'ids', type: 'uint256[]' },
      {
        components: [
          { internalType: 'address', name: 'client', type: 'address' },
          { internalType: 'uint256', name: 'serviceId', type: 'uint256' },
          { internalType: 'uint256', name: 'amount', type: 'uint256' },
          { internalType: 'uint256', name: 'deadlineDays', type: 'uint256' },
          { internalType: 'bytes32', name: 'termsHash', type: 'bytes32' },
          { internalType: 'uint8', name: 'region', type: 'uint8' },
          { internalType: 'uint8', name: 'status', type: 'uint8' },
          { internalType: 'uint256', name: 'createdAt', type: 'uint256' },
          { internalType: 'address', name: 'agreement', type: 'address' },
        ],
        internalType: 'struct ServiceBoardStorage.HireRequest[]',
        name: 'pendingReqs',
        type: 'tuple[]',
      },
    ],
    stateMutability: 'view',
    type: 'function',
  },

  // === JobBoardFacet ===
  {
    inputs: [
      { internalType: 'address', name: 'client', type: 'address' },
      { internalType: 'string', name: 'title', type: 'string' },
      { internalType: 'string', name: 'description', type: 'string' },
      { internalType: 'uint256', name: 'amount', type: 'uint256' },
      { internalType: 'uint256', name: 'deadlineDays', type: 'uint256' },
      { internalType: 'bytes32', name: 'termsHash', type: 'bytes32' },
      { internalType: 'uint8', name: 'region', type: 'uint8' },
      { internalType: 'uint256', name: 'permitDeadline', type: 'uint256' },
      { internalType: 'uint8', name: 'v', type: 'uint8' },
      { internalType: 'bytes32', name: 'r', type: 'bytes32' },
      { internalType: 'bytes32', name: 's', type: 'bytes32' },
    ],
    name: 'mintJobWithPermit',
    outputs: [{ internalType: 'uint256', name: 'jobId', type: 'uint256' }],
    stateMutability: 'nonpayable',
    type: 'function',
  },
  {
    inputs: [{ internalType: 'uint256', name: 'jobId', type: 'uint256' }],
    name: 'applyForJob',
    outputs: [],
    stateMutability: 'nonpayable',
    type: 'function',
  },
  {
    inputs: [
      { internalType: 'uint256', name: 'jobId', type: 'uint256' },
      { internalType: 'address', name: 'executor', type: 'address' },
    ],
    name: 'acceptApplicant',
    outputs: [{ internalType: 'address', name: 'agreementAddr', type: 'address' }],
    stateMutability: 'nonpayable',
    type: 'function',
  },
  {
    inputs: [{ internalType: 'uint256', name: 'jobId', type: 'uint256' }],
    name: 'cancelJob',
    outputs: [],
    stateMutability: 'nonpayable',
    type: 'function',
  },
  {
    inputs: [
      { internalType: 'uint256', name: 'jobId', type: 'uint256' },
      { internalType: 'string', name: 'title', type: 'string' },
      { internalType: 'string', name: 'description', type: 'string' },
      { internalType: 'uint256', name: 'deadlineDays', type: 'uint256' },
      { internalType: 'bytes32', name: 'termsHash', type: 'bytes32' },
      { internalType: 'uint8', name: 'region', type: 'uint8' },
    ],
    name: 'editJob',
    outputs: [],
    stateMutability: 'nonpayable',
    type: 'function',
  },
  {
    inputs: [
      { internalType: 'uint256', name: 'serviceId', type: 'uint256' },
      { internalType: 'string', name: 'title', type: 'string' },
      { internalType: 'string', name: 'description', type: 'string' },
      { internalType: 'uint256', name: 'price', type: 'uint256' },
      { internalType: 'uint256', name: 'deadlineDays', type: 'uint256' },
      { internalType: 'uint8', name: 'region', type: 'uint8' },
    ],
    name: 'editService',
    outputs: [],
    stateMutability: 'nonpayable',
    type: 'function',
  },
  {
    inputs: [{ internalType: 'uint256', name: 'jobId', type: 'uint256' }],
    name: 'getJob',
    outputs: [
      {
        components: [
          { internalType: 'address', name: 'client', type: 'address' },
          { internalType: 'string', name: 'title', type: 'string' },
          { internalType: 'string', name: 'description', type: 'string' },
          { internalType: 'uint256', name: 'amount', type: 'uint256' },
          { internalType: 'uint256', name: 'deadlineDays', type: 'uint256' },
          { internalType: 'bytes32', name: 'termsHash', type: 'bytes32' },
          { internalType: 'uint8', name: 'region', type: 'uint8' },
          { internalType: 'uint8', name: 'status', type: 'uint8' },
          { internalType: 'uint256', name: 'createdAt', type: 'uint256' },
          { internalType: 'address', name: 'chosenExecutor', type: 'address' },
          { internalType: 'address', name: 'agreement', type: 'address' },
        ],
        internalType: 'struct JobBoardStorage.Job',
        name: '',
        type: 'tuple',
      },
    ],
    stateMutability: 'view',
    type: 'function',
  },
  {
    inputs: [],
    name: 'getOpenJobs',
    outputs: [
      { internalType: 'uint256[]', name: 'ids', type: 'uint256[]' },
      {
        components: [
          { internalType: 'address', name: 'client', type: 'address' },
          { internalType: 'string', name: 'title', type: 'string' },
          { internalType: 'string', name: 'description', type: 'string' },
          { internalType: 'uint256', name: 'amount', type: 'uint256' },
          { internalType: 'uint256', name: 'deadlineDays', type: 'uint256' },
          { internalType: 'bytes32', name: 'termsHash', type: 'bytes32' },
          { internalType: 'uint8', name: 'region', type: 'uint8' },
          { internalType: 'uint8', name: 'status', type: 'uint8' },
          { internalType: 'uint256', name: 'createdAt', type: 'uint256' },
          { internalType: 'address', name: 'chosenExecutor', type: 'address' },
          { internalType: 'address', name: 'agreement', type: 'address' },
        ],
        internalType: 'struct JobBoardStorage.Job[]',
        name: 'openJobs',
        type: 'tuple[]',
      },
    ],
    stateMutability: 'view',
    type: 'function',
  },
  {
    inputs: [{ internalType: 'address', name: 'client', type: 'address' }],
    name: 'getClientJobs',
    outputs: [{ internalType: 'uint256[]', name: '', type: 'uint256[]' }],
    stateMutability: 'view',
    type: 'function',
  },
  {
    inputs: [{ internalType: 'uint256', name: 'jobId', type: 'uint256' }],
    name: 'getApplicants',
    outputs: [{ internalType: 'address[]', name: '', type: 'address[]' }],
    stateMutability: 'view',
    type: 'function',
  },
  {
    inputs: [],
    name: 'totalJobs',
    outputs: [{ internalType: 'uint256', name: '', type: 'uint256' }],
    stateMutability: 'view',
    type: 'function',
  },
  {
    anonymous: false,
    inputs: [
      { indexed: true, internalType: 'uint256', name: 'jobId', type: 'uint256' },
      { indexed: true, internalType: 'address', name: 'client', type: 'address' },
      { indexed: false, internalType: 'uint256', name: 'amount', type: 'uint256' },
      { indexed: false, internalType: 'uint8', name: 'region', type: 'uint8' },
    ],
    name: 'JobPosted',
    type: 'event',
  },
  {
    anonymous: false,
    inputs: [
      { indexed: true, internalType: 'uint256', name: 'jobId', type: 'uint256' },
      { indexed: true, internalType: 'address', name: 'executor', type: 'address' },
    ],
    name: 'JobApplied',
    type: 'event',
  },
  {
    anonymous: false,
    inputs: [
      { indexed: true, internalType: 'uint256', name: 'jobId', type: 'uint256' },
      { indexed: true, internalType: 'address', name: 'client', type: 'address' },
      { indexed: true, internalType: 'address', name: 'executor', type: 'address' },
      { indexed: false, internalType: 'address', name: 'agreement', type: 'address' },
    ],
    name: 'JobAccepted',
    type: 'event',
  },
  {
    anonymous: false,
    inputs: [
      { indexed: true, internalType: 'uint256', name: 'jobId', type: 'uint256' },
      { indexed: true, internalType: 'address', name: 'client', type: 'address' },
      { indexed: false, internalType: 'uint256', name: 'refundAmount', type: 'uint256' },
    ],
    name: 'JobCancelled',
    type: 'event',
  },

  // === OwnershipFacet ===
  {
    inputs: [],
    name: 'owner',
    outputs: [{ internalType: 'address', name: '', type: 'address' }],
    stateMutability: 'view',
    type: 'function',
  },

  // === DiamondLoupeFacet ===
  {
    inputs: [],
    name: 'facets',
    outputs: [
      {
        components: [
          { internalType: 'address', name: 'facetAddress', type: 'address' },
          { internalType: 'bytes4[]', name: 'functionSelectors', type: 'bytes4[]' },
        ],
        internalType: 'struct IDiamondLoupe.Facet[]',
        name: 'facets_',
        type: 'tuple[]',
      },
    ],
    stateMutability: 'view',
    type: 'function',
  },

  // === Events ===
  {
    anonymous: false,
    inputs: [
      { indexed: true, internalType: 'address', name: 'agreement', type: 'address' },
      { indexed: true, internalType: 'address', name: 'client', type: 'address' },
      { indexed: true, internalType: 'address', name: 'executor', type: 'address' },
      { indexed: false, internalType: 'uint256', name: 'amount', type: 'uint256' },
    ],
    name: 'AgreementRegistered',
    type: 'event',
  },
  {
    anonymous: false,
    inputs: [
      { indexed: true, internalType: 'address', name: 'agreement', type: 'address' },
      { indexed: true, internalType: 'address', name: 'client', type: 'address' },
      { indexed: true, internalType: 'address', name: 'executor', type: 'address' },
      { indexed: false, internalType: 'uint256', name: 'amount', type: 'uint256' },
      { indexed: false, internalType: 'uint8', name: 'region', type: 'uint8' },
      { indexed: false, internalType: 'uint256', name: 'fee', type: 'uint256' },
    ],
    name: 'AgreementDeployed',
    type: 'event',
  },
  {
    anonymous: false,
    inputs: [
      { indexed: true, internalType: 'address', name: 'agreement', type: 'address' },
      { indexed: false, internalType: 'uint8', name: 'newStatus', type: 'uint8' },
    ],
    name: 'AgreementStatusUpdated',
    type: 'event',
  },
  {
    anonymous: false,
    inputs: [
      { indexed: true, internalType: 'address', name: 'arbiter', type: 'address' },
    ],
    name: 'ProtocolArbiterUpdated',
    type: 'event',
  },
];

// ServiceBoardFacet events (all on Diamond address)
export const SERVICE_BOARD_ABI = [
  {
    anonymous: false,
    inputs: [
      { indexed: true,  internalType: 'uint256', name: 'serviceId', type: 'uint256' },
      { indexed: true,  internalType: 'address', name: 'executor',  type: 'address' },
      { indexed: false, internalType: 'uint256', name: 'price',     type: 'uint256' },
      { indexed: false, internalType: 'uint8',   name: 'region',    type: 'uint8'   },
    ],
    name: 'ServicePosted',
    type: 'event',
  },
  {
    anonymous: false,
    inputs: [
      { indexed: true,  internalType: 'uint256', name: 'requestId', type: 'uint256' },
      { indexed: true,  internalType: 'uint256', name: 'serviceId', type: 'uint256' },
      { indexed: true,  internalType: 'address', name: 'client',    type: 'address' },
      { indexed: false, internalType: 'uint256', name: 'amount',    type: 'uint256' },
    ],
    name: 'ServiceRequested',
    type: 'event',
  },
  {
    anonymous: false,
    inputs: [
      { indexed: true,  internalType: 'uint256', name: 'requestId', type: 'uint256' },
      { indexed: true,  internalType: 'address', name: 'executor',  type: 'address' },
      { indexed: true,  internalType: 'address', name: 'client',    type: 'address' },
      { indexed: false, internalType: 'address', name: 'agreement', type: 'address' },
    ],
    name: 'RequestAccepted',
    type: 'event',
  },
  {
    anonymous: false,
    inputs: [
      { indexed: true, internalType: 'uint256', name: 'requestId', type: 'uint256' },
      { indexed: true, internalType: 'address', name: 'executor',  type: 'address' },
      { indexed: true, internalType: 'address', name: 'client',    type: 'address' },
    ],
    name: 'RequestRejected',
    type: 'event',
  },
  {
    anonymous: false,
    inputs: [
      { indexed: true, internalType: 'uint256', name: 'requestId', type: 'uint256' },
      { indexed: true, internalType: 'address', name: 'client',    type: 'address' },
    ],
    name: 'RequestCancelled',
    type: 'event',
  },
  {
    anonymous: false,
    inputs: [
      { indexed: true, internalType: 'uint256', name: 'serviceId', type: 'uint256' },
      { indexed: true, internalType: 'address', name: 'executor',  type: 'address' },
    ],
    name: 'ServiceRemoved',
    type: 'event',
  },
] as const;

// USDC ABI (минимальный)
export const USDC_ABI = [
  {
    inputs: [{ internalType: 'address', name: 'account', type: 'address' }],
    name: 'balanceOf',
    outputs: [{ internalType: 'uint256', name: '', type: 'uint256' }],
    stateMutability: 'view',
    type: 'function',
  },
  {
    inputs: [
      { internalType: 'address', name: 'spender', type: 'address' },
      { internalType: 'uint256', name: 'amount', type: 'uint256' },
    ],
    name: 'approve',
    outputs: [{ internalType: 'bool', name: '', type: 'bool' }],
    stateMutability: 'nonpayable',
    type: 'function',
  },
  {
    inputs: [
      { internalType: 'address', name: 'owner', type: 'address' },
      { internalType: 'address', name: 'spender', type: 'address' },
    ],
    name: 'allowance',
    outputs: [{ internalType: 'uint256', name: '', type: 'uint256' }],
    stateMutability: 'view',
    type: 'function',
  },
  {
    inputs: [],
    name: 'decimals',
    outputs: [{ internalType: 'uint8', name: '', type: 'uint8' }],
    stateMutability: 'view',
    type: 'function',
  },
  {
    inputs: [{ internalType: 'address', name: 'owner', type: 'address' }],
    name: 'nonces',
    outputs: [{ internalType: 'uint256', name: '', type: 'uint256' }],
    stateMutability: 'view',
    type: 'function',
  },
  {
    anonymous: false,
    inputs: [
      { indexed: true, internalType: 'address', name: 'owner', type: 'address' },
      { indexed: true, internalType: 'address', name: 'spender', type: 'address' },
      { indexed: false, internalType: 'uint256', name: 'value', type: 'uint256' },
    ],
    name: 'Approval',
    type: 'event',
  },
];

// MinimalForwarder ABI
export const FORWARDER_ABI = [
  {
    inputs: [{ internalType: 'address', name: 'from', type: 'address' }],
    name: 'getNonce',
    outputs: [{ internalType: 'uint256', name: '', type: 'uint256' }],
    stateMutability: 'view',
    type: 'function',
  },
  {
    inputs: [
      {
        components: [
          { internalType: 'address', name: 'from', type: 'address' },
          { internalType: 'address', name: 'to', type: 'address' },
          { internalType: 'uint256', name: 'value', type: 'uint256' },
          { internalType: 'uint256', name: 'gas', type: 'uint256' },
          { internalType: 'uint256', name: 'nonce', type: 'uint256' },
          { internalType: 'bytes', name: 'data', type: 'bytes' },
        ],
        internalType: 'struct MinimalForwarder.ForwardRequest',
        name: 'req',
        type: 'tuple',
      },
      { internalType: 'bytes', name: 'signature', type: 'bytes' },
    ],
    name: 'execute',
    outputs: [
      { internalType: 'bool', name: 'success', type: 'bool' },
      { internalType: 'bytes', name: 'retdata', type: 'bytes' },
    ],
    stateMutability: 'payable',
    type: 'function',
  },
  {
    inputs: [
      {
        components: [
          { internalType: 'address', name: 'from', type: 'address' },
          { internalType: 'address', name: 'to', type: 'address' },
          { internalType: 'uint256', name: 'value', type: 'uint256' },
          { internalType: 'uint256', name: 'gas', type: 'uint256' },
          { internalType: 'uint256', name: 'nonce', type: 'uint256' },
          { internalType: 'bytes', name: 'data', type: 'bytes' },
        ],
        internalType: 'struct MinimalForwarder.ForwardRequest',
        name: 'req',
        type: 'tuple',
      },
      { internalType: 'bytes', name: 'signature', type: 'bytes' },
    ],
    name: 'verify',
    outputs: [{ internalType: 'bool', name: '', type: 'bool' }],
    stateMutability: 'view',
    type: 'function',
  },
];

// Agreement ABI (для взаимодействия с отдельными Agreement контрактами)
export const AGREEMENT_ABI = [
  {
    inputs: [],
    name: 'status',
    outputs: [{ internalType: 'uint8', name: '', type: 'uint8' }],
    stateMutability: 'view',
    type: 'function',
  },
  {
    inputs: [],
    name: 'client',
    outputs: [{ internalType: 'address', name: '', type: 'address' }],
    stateMutability: 'view',
    type: 'function',
  },
  {
    inputs: [],
    name: 'executor',
    outputs: [{ internalType: 'address', name: '', type: 'address' }],
    stateMutability: 'view',
    type: 'function',
  },
  {
    inputs: [],
    name: 'amount',
    outputs: [{ internalType: 'uint256', name: '', type: 'uint256' }],
    stateMutability: 'view',
    type: 'function',
  },
  {
    inputs: [],
    name: 'fundedAt',
    outputs: [{ internalType: 'uint256', name: '', type: 'uint256' }],
    stateMutability: 'view',
    type: 'function',
  },
  {
    inputs: [],
    name: 'activatedAt',
    outputs: [{ internalType: 'uint256', name: '', type: 'uint256' }],
    stateMutability: 'view',
    type: 'function',
  },
  {
    inputs: [],
    name: 'markedDoneAt',
    outputs: [{ internalType: 'uint256', name: '', type: 'uint256' }],
    stateMutability: 'view',
    type: 'function',
  },
  {
    inputs: [],
    name: 'disputedAt',
    outputs: [{ internalType: 'uint256', name: '', type: 'uint256' }],
    stateMutability: 'view',
    type: 'function',
  },
  {
    inputs: [],
    name: 'resolvedAt',
    outputs: [{ internalType: 'uint256', name: '', type: 'uint256' }],
    stateMutability: 'view',
    type: 'function',
  },
  {
    inputs: [],
    name: 'deadlineDays',
    outputs: [{ internalType: 'uint256', name: '', type: 'uint256' }],
    stateMutability: 'view',
    type: 'function',
  },
  {
    inputs: [],
    name: 'timeLeft',
    outputs: [{ internalType: 'uint256', name: '', type: 'uint256' }],
    stateMutability: 'view',
    type: 'function',
  },
  {
    inputs: [],
    name: 'fund',
    outputs: [],
    stateMutability: 'nonpayable',
    type: 'function',
  },
  {
    inputs: [],
    name: 'activate',
    outputs: [],
    stateMutability: 'nonpayable',
    type: 'function',
  },
  {
    inputs: [],
    name: 'markDone',
    outputs: [],
    stateMutability: 'nonpayable',
    type: 'function',
  },
  {
    inputs: [],
    name: 'release',
    outputs: [],
    stateMutability: 'nonpayable',
    type: 'function',
  },
  {
    inputs: [],
    name: 'triggerAutoApprove',
    outputs: [],
    stateMutability: 'nonpayable',
    type: 'function',
  },
  {
    inputs: [],
    name: 'raiseDispute',
    outputs: [],
    stateMutability: 'nonpayable',
    type: 'function',
  },
  {
    inputs: [{ internalType: 'bool', name: 'clientWins', type: 'bool' }],
    name: 'resolveDispute',
    outputs: [],
    stateMutability: 'nonpayable',
    type: 'function',
  },
  {
    inputs: [],
    name: 'triggerActivationTimeout',
    outputs: [],
    stateMutability: 'nonpayable',
    type: 'function',
  },
  {
    inputs: [],
    name: 'triggerDeadlineTimeout',
    outputs: [],
    stateMutability: 'nonpayable',
    type: 'function',
  },
  {
    inputs: [],
    name: 'triggerArbiterTimeout',
    outputs: [],
    stateMutability: 'nonpayable',
    type: 'function',
  },
  {
    inputs: [{ internalType: 'uint256', name: 'tokenId', type: 'uint256' }],
    name: 'ownerOf',
    outputs: [{ internalType: 'address', name: '', type: 'address' }],
    stateMutability: 'view',
    type: 'function',
  },
  {
    inputs: [],
    name: 'getDetails',
    outputs: [
      { internalType: 'address', name: 'client_', type: 'address' },
      { internalType: 'address', name: 'executor_', type: 'address' },
      { internalType: 'address', name: 'arbiter_', type: 'address' },
      { internalType: 'uint256', name: 'amount_', type: 'uint256' },
      { internalType: 'bytes32', name: 'termsHash_', type: 'bytes32' },
      { internalType: 'uint256', name: 'deadlineDays_', type: 'uint256' },
      { internalType: 'uint256', name: 'fundedAt_', type: 'uint256' },
      { internalType: 'uint256', name: 'activatedAt_', type: 'uint256' },
      { internalType: 'uint256', name: 'markedDoneAt_', type: 'uint256' },
      { internalType: 'uint256', name: 'disputedAt_', type: 'uint256' },
      { internalType: 'uint256', name: 'resolvedAt_', type: 'uint256' },
      { internalType: 'uint8',   name: 'status_',     type: 'uint8' },
    ],
    stateMutability: 'view',
    type: 'function',
  },
  {
    inputs: [],
    name: 'arbiterTimeLeft',
    outputs: [{ internalType: 'uint256', name: '', type: 'uint256' }],
    stateMutability: 'view',
    type: 'function',
  },
  // ── Extras ──
  {
    inputs: [
      { internalType: 'uint256', name: 'extraAmount', type: 'uint256' },
      { internalType: 'bytes32', name: 'extraTermsHash', type: 'bytes32' },
    ],
    name: 'proposeExtra',
    outputs: [],
    stateMutability: 'nonpayable',
    type: 'function',
  },
  {
    inputs: [{ internalType: 'uint256', name: 'extraId', type: 'uint256' }],
    name: 'acceptExtra',
    outputs: [],
    stateMutability: 'nonpayable',
    type: 'function',
  },
  {
    inputs: [{ internalType: 'uint256', name: 'extraId', type: 'uint256' }],
    name: 'rejectExtra',
    outputs: [],
    stateMutability: 'nonpayable',
    type: 'function',
  },
  {
    inputs: [{ internalType: 'uint256', name: 'extraId', type: 'uint256' }],
    name: 'getExtra',
    outputs: [
      {
        components: [
          { internalType: 'uint256', name: 'amount', type: 'uint256' },
          { internalType: 'bytes32', name: 'termsHash', type: 'bytes32' },
          { internalType: 'uint8',   name: 'status',    type: 'uint8' },
        ],
        internalType: 'struct Agreement.Extra',
        name: '',
        type: 'tuple',
      },
    ],
    stateMutability: 'view',
    type: 'function',
  },
  {
    inputs: [],
    name: 'totalPayout',
    outputs: [{ internalType: 'uint256', name: '', type: 'uint256' }],
    stateMutability: 'view',
    type: 'function',
  },
  {
    inputs: [],
    name: 'nextExtraId',
    outputs: [{ internalType: 'uint256', name: '', type: 'uint256' }],
    stateMutability: 'view',
    type: 'function',
  },
  {
    inputs: [],
    name: 'extrasTotal',
    outputs: [{ internalType: 'uint256', name: '', type: 'uint256' }],
    stateMutability: 'view',
    type: 'function',
  },
];

// Адреса контрактов
export const CONTRACTS = {
  diamond:    (process.env.NEXT_PUBLIC_DIAMOND_ADDRESS     || '0x7A91d700CF2a201E99F0aD3C3b4f4D79CFE69557') as `0x${string}`,
  forwarder:  (process.env.NEXT_PUBLIC_FORWARDER_ADDRESS   || '0x41c66b80B1445F48AF3863763BC0EC0549413CD7') as `0x${string}`,
  usdc:       (process.env.NEXT_PUBLIC_USDC_ADDRESS        || '0x036CbD53842c5426634e7929541eC2318f3dCF7e') as `0x${string}`,
  jobReceipt: (process.env.NEXT_PUBLIC_JOB_RECEIPT_ADDRESS || '0x0000000000000000000000000000000000000000') as `0x${string}`,
} as const;

// PlatformReceiptNFT ABI — standalone contract, не Diamond facet
// Обрабатывает чеки для JOB (зелёные) и OFFER (фиолетовые)
export const JOB_RECEIPT_NFT_ABI = [
  // ── Views ──
  {
    inputs: [{ internalType: 'uint256', name: 'jobId', type: 'uint256' }],
    name: 'jobClaimed',
    outputs: [{ internalType: 'bool', name: '', type: 'bool' }],
    stateMutability: 'view',
    type: 'function',
  },
  {
    inputs: [{ internalType: 'uint256', name: 'offerId', type: 'uint256' }],
    name: 'offerClaimed',
    outputs: [{ internalType: 'bool', name: '', type: 'bool' }],
    stateMutability: 'view',
    type: 'function',
  },
  {
    inputs: [{ internalType: 'uint256', name: 'tokenId', type: 'uint256' }],
    name: 'tokenReceiptType',
    outputs: [{ internalType: 'uint8', name: '', type: 'uint8' }],
    stateMutability: 'view',
    type: 'function',
  },
  {
    inputs: [{ internalType: 'uint256', name: 'tokenId', type: 'uint256' }],
    name: 'tokenURI',
    outputs: [{ internalType: 'string', name: '', type: 'string' }],
    stateMutability: 'view',
    type: 'function',
  },
  {
    inputs: [{ internalType: 'address', name: 'owner', type: 'address' }],
    name: 'balanceOf',
    outputs: [{ internalType: 'uint256', name: '', type: 'uint256' }],
    stateMutability: 'view',
    type: 'function',
  },
  // ── Fallback claim (если авто-минт не сработал) ──
  {
    inputs: [{ internalType: 'uint256', name: 'jobId', type: 'uint256' }],
    name: 'claimReceipt',
    outputs: [{ internalType: 'uint256', name: 'tokenId', type: 'uint256' }],
    stateMutability: 'nonpayable',
    type: 'function',
  },
  // ── Event ──
  {
    anonymous: false,
    inputs: [
      { indexed: true,  internalType: 'uint256', name: 'tokenId',     type: 'uint256' },
      { indexed: false, internalType: 'uint8',   name: 'receiptType', type: 'uint8'   },
      { indexed: true,  internalType: 'uint256', name: 'refId',       type: 'uint256' },
      { indexed: true,  internalType: 'address', name: 'owner',       type: 'address' },
    ],
    name: 'ReceiptMinted',
    type: 'event',
  },
] as const;

// PPP регионы
export const REGIONS = {
  CIS: 0,
  ASIA: 1,
  EU: 2,
  US: 3,
  LATAM: 4,
  CA: 5,
  AU: 6,
} as const;

// Статусы сделок
export const AGREEMENT_STATUS = {
  ACTIVE: 0,
  COMPLETED: 1,
  REFUNDED: 2,
  DISPUTED: 3,
  RESOLVED: 4,
} as const;

export const STATUS_LABELS: Record<number, string> = {
  0: 'Active',
  1: 'Completed',
  2: 'Refunded',
  3: 'Disputed',
  4: 'Resolved',
};

// JobReceiptFacet ABI (part of Diamond) — replaces OfferNFTFacet
export const JOB_RECEIPT_FACET_ABI = [
  {
    inputs: [
      { internalType: 'address', name: 'to', type: 'address' },
      { internalType: 'uint256', name: 'jobId', type: 'uint256' },
      { internalType: 'uint256', name: 'amount', type: 'uint256' },
      { internalType: 'uint256', name: 'deadlineDays', type: 'uint256' },
      { internalType: 'uint8', name: 'region', type: 'uint8' },
      { internalType: 'string', name: 'title', type: 'string' },
    ],
    name: 'mintJobReceipt',
    outputs: [{ internalType: 'uint256', name: 'tokenId', type: 'uint256' }],
    stateMutability: 'nonpayable',
    type: 'function',
  },
  {
    inputs: [{ internalType: 'uint256', name: 'tokenId', type: 'uint256' }],
    name: 'getJobReceiptData',
    outputs: [
      {
        internalType: 'struct ReceiptStorage.JobReceiptData',
        name: '',
        type: 'tuple',
        components: [
          { internalType: 'address', name: 'client', type: 'address' },
          { internalType: 'string', name: 'title', type: 'string' },
          { internalType: 'uint256', name: 'amount', type: 'uint256' },
          { internalType: 'uint256', name: 'deadlineDays', type: 'uint256' },
          { internalType: 'uint8', name: 'region', type: 'uint8' },
          { internalType: 'uint256', name: 'createdAt', type: 'uint256' },
        ],
      },
    ],
    stateMutability: 'view',
    type: 'function',
  },
  {
    inputs: [{ internalType: 'uint256', name: 'tokenId', type: 'uint256' }],
    name: 'isJobReceiptToken',
    outputs: [{ internalType: 'bool', name: '', type: 'bool' }],
    stateMutability: 'view',
    type: 'function',
  },
  {
    inputs: [],
    name: 'getReceiptTotalSupply',
    outputs: [{ internalType: 'uint256', name: '', type: 'uint256' }],
    stateMutability: 'view',
    type: 'function',
  },
  {
    inputs: [{ internalType: 'address', name: 'renderer', type: 'address' }],
    name: 'setSvgRenderer',
    outputs: [],
    stateMutability: 'nonpayable',
    type: 'function',
  },
  {
    inputs: [],
    name: 'getSvgRenderer',
    outputs: [{ internalType: 'address', name: '', type: 'address' }],
    stateMutability: 'view',
    type: 'function',
  },
  {
    inputs: [],
    name: 'name',
    outputs: [{ internalType: 'string', name: '', type: 'string' }],
    stateMutability: 'pure',
    type: 'function',
  },
  {
    inputs: [],
    name: 'symbol',
    outputs: [{ internalType: 'string', name: '', type: 'string' }],
    stateMutability: 'pure',
    type: 'function',
  },
  {
    inputs: [{ internalType: 'address', name: 'owner', type: 'address' }],
    name: 'balanceOf',
    outputs: [{ internalType: 'uint256', name: '', type: 'uint256' }],
    stateMutability: 'view',
    type: 'function',
  },
  {
    inputs: [{ internalType: 'uint256', name: 'tokenId', type: 'uint256' }],
    name: 'ownerOf',
    outputs: [{ internalType: 'address', name: '', type: 'address' }],
    stateMutability: 'view',
    type: 'function',
  },
  {
    inputs: [{ internalType: 'uint256', name: 'tokenId', type: 'uint256' }],
    name: 'tokenURI',
    outputs: [{ internalType: 'string', name: '', type: 'string' }],
    stateMutability: 'view',
    type: 'function',
  },
  {
    anonymous: false,
    inputs: [
      { indexed: true, internalType: 'address', name: 'owner', type: 'address' },
      { indexed: true, internalType: 'address', name: 'approved', type: 'address' },
      { indexed: true, internalType: 'uint256', name: 'tokenId', type: 'uint256' },
    ],
    name: 'Approval',
    type: 'event',
  },
  {
    anonymous: false,
    inputs: [
      { indexed: true, internalType: 'address', name: 'owner', type: 'address' },
      { indexed: true, internalType: 'address', name: 'operator', type: 'address' },
      { indexed: false, internalType: 'bool', name: 'approved', type: 'bool' },
    ],
    name: 'ApprovalForAll',
    type: 'event',
  },
  {
    anonymous: false,
    inputs: [
      { indexed: true, internalType: 'address', name: 'from', type: 'address' },
      { indexed: true, internalType: 'address', name: 'to', type: 'address' },
      { indexed: true, internalType: 'uint256', name: 'tokenId', type: 'uint256' },
    ],
    name: 'Transfer',
    type: 'event',
  },
];

// ArbiterRegistryFacet ABI (part of Diamond)
export const ARBITER_REGISTRY_ABI = [
  // Admin
  {
    inputs: [{ internalType: 'address', name: 'arbiter', type: 'address' }],
    name: 'setChiefArbiter',
    outputs: [],
    stateMutability: 'nonpayable',
    type: 'function',
  },
  {
    inputs: [{ internalType: 'address', name: 'arbiter', type: 'address' }],
    name: 'addArbiter',
    outputs: [],
    stateMutability: 'nonpayable',
    type: 'function',
  },
  {
    inputs: [{ internalType: 'address', name: 'arbiter', type: 'address' }],
    name: 'removeArbiter',
    outputs: [],
    stateMutability: 'nonpayable',
    type: 'function',
  },
  // Arbiter actions
  {
    inputs: [{ internalType: 'address', name: 'agreement', type: 'address' }],
    name: 'claimDispute',
    outputs: [],
    stateMutability: 'nonpayable',
    type: 'function',
  },
  {
    inputs: [{ internalType: 'address', name: 'agreement', type: 'address' }],
    name: 'releaseDisputeClaim',
    outputs: [],
    stateMutability: 'nonpayable',
    type: 'function',
  },
  // Views
  {
    inputs: [{ internalType: 'address', name: 'addr', type: 'address' }],
    name: 'isRegisteredArbiter',
    outputs: [{ internalType: 'bool', name: '', type: 'bool' }],
    stateMutability: 'view',
    type: 'function',
  },
  {
    inputs: [],
    name: 'getChiefArbiter',
    outputs: [{ internalType: 'address', name: '', type: 'address' }],
    stateMutability: 'view',
    type: 'function',
  },
  {
    inputs: [],
    name: 'getArbiters',
    outputs: [{ internalType: 'address[]', name: '', type: 'address[]' }],
    stateMutability: 'view',
    type: 'function',
  },
  {
    inputs: [{ internalType: 'address', name: 'agreement', type: 'address' }],
    name: 'getDisputeClaimer',
    outputs: [{ internalType: 'address', name: '', type: 'address' }],
    stateMutability: 'view',
    type: 'function',
  },
  {
    inputs: [{ internalType: 'address', name: 'arbiter', type: 'address' }],
    name: 'getArbiterDeals',
    outputs: [{ internalType: 'address[]', name: '', type: 'address[]' }],
    stateMutability: 'view',
    type: 'function',
  },
  // Events
  {
    anonymous: false,
    inputs: [{ indexed: true, internalType: 'address', name: 'arbiter', type: 'address' }],
    name: 'ArbiterAdded',
    type: 'event',
  },
  {
    anonymous: false,
    inputs: [{ indexed: true, internalType: 'address', name: 'arbiter', type: 'address' }],
    name: 'ArbiterRemoved',
    type: 'event',
  },
  {
    anonymous: false,
    inputs: [
      { indexed: true, internalType: 'address', name: 'agreement', type: 'address' },
      { indexed: true, internalType: 'address', name: 'arbiter', type: 'address' },
    ],
    name: 'DisputeClaimed',
    type: 'event',
  },
  {
    anonymous: false,
    inputs: [
      { indexed: true, internalType: 'address', name: 'agreement', type: 'address' },
      { indexed: true, internalType: 'address', name: 'prevArbiter', type: 'address' },
    ],
    name: 'DisputeReleased',
    type: 'event',
  },
] as const;
